module.exports = [
  {
    name: '> tree-shaking: VkIcon',
    path: './dist/icons.esm.js',
    import: '{ VkIcon }',
    running: false,
    limit: '1 KB',
  },
  {
    name: '> tree-shaking: CloseIcon',
    path: './dist/icons.esm.js',
    import: '{ CloseIcon }',
    running: false,
    limit: '414 B',
  },
  {
    name: '> tree-shaking: FlameIcon',
    path: './dist/icons.esm.js',
    import: '{ FlameIcon }',
    running: false,
    limit: '785 B',
  },
  {
    name: '> tree-shaking: MapIcon',
    path: './dist/icons.esm.js',
    import: '{ MapIcon }',
    running: false,
    limit: '490 B',
  },
  {
    name: '> tree-shaking: TvIcon',
    path: './dist/icons.esm.js',
    import: '{ TvIcon }',
    running: false,
    limit: '481 B',
  },
  {
    name: '> tree-shaking: ActiveIcon',
    path: './dist/icons.esm.js',
    import: '{ ActiveIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: AddIcon',
    path: './dist/icons.esm.js',
    import: '{ AddIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: AddressIcon',
    path: './dist/icons.esm.js',
    import: '{ AddressIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: AlertIcon',
    path: './dist/icons.esm.js',
    import: '{ AlertIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: AllActionsFillIcon',
    path: './dist/icons.esm.js',
    import: '{ AllActionsFillIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: AllActionsIcon',
    path: './dist/icons.esm.js',
    import: '{ AllActionsIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: AppleIcon',
    path: './dist/icons.esm.js',
    import: '{ AppleIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: AreaIcon',
    path: './dist/icons.esm.js',
    import: '{ AreaIcon }',
    running: false,
    limit: '1.14 KB',
  },
  {
    name: '> tree-shaking: ArrowIcon',
    path: './dist/icons.esm.js',
    import: '{ ArrowIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: AvatarIcon',
    path: './dist/icons.esm.js',
    import: '{ AvatarIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: BackIcon',
    path: './dist/icons.esm.js',
    import: '{ BackIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: BarsIcon',
    path: './dist/icons.esm.js',
    import: '{ BarsIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: BusIcon',
    path: './dist/icons.esm.js',
    import: '{ BusIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CalendarIcon',
    path: './dist/icons.esm.js',
    import: '{ CalendarIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CallIcon',
    path: './dist/icons.esm.js',
    import: '{ CallIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CameraFillIcon',
    path: './dist/icons.esm.js',
    import: '{ CameraFillIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CameraIcon',
    path: './dist/icons.esm.js',
    import: '{ CameraIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CheckGroupIcon',
    path: './dist/icons.esm.js',
    import: '{ CheckGroupIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CheckIcon',
    path: './dist/icons.esm.js',
    import: '{ CheckIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ChevronDoubleLeftIcon',
    path: './dist/icons.esm.js',
    import: '{ ChevronDoubleLeftIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ChevronDoubleUpIcon',
    path: './dist/icons.esm.js',
    import: '{ ChevronDoubleUpIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CloseRoundedRedIcon',
    path: './dist/icons.esm.js',
    import: '{ CloseRoundedRedIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CloseRoundedWhiteIcon',
    path: './dist/icons.esm.js',
    import: '{ CloseRoundedWhiteIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CommentIcon',
    path: './dist/icons.esm.js',
    import: '{ CommentIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ComplainIcon',
    path: './dist/icons.esm.js',
    import: '{ ComplainIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ConditionerIcon',
    path: './dist/icons.esm.js',
    import: '{ ConditionerIcon }',
    running: false,
    limit: '914 B',
  },
  {
    name: '> tree-shaking: CookerIcon',
    path: './dist/icons.esm.js',
    import: '{ CookerIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CopyIcon',
    path: './dist/icons.esm.js',
    import: '{ CopyIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: CurrencyIcon',
    path: './dist/icons.esm.js',
    import: '{ CurrencyIcon }',
    running: false,
    limit: '1.07 KB',
  },
  {
    name: '> tree-shaking: DangerIcon',
    path: './dist/icons.esm.js',
    import: '{ DangerIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: DeleteProfileIcon',
    path: './dist/icons.esm.js',
    import: '{ DeleteProfileIcon }',
    running: false,
    limit: '1.35 KB',
  },
  {
    name: '> tree-shaking: DeliveredIcon',
    path: './dist/icons.esm.js',
    import: '{ DeliveredIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: DishwasherIcon',
    path: './dist/icons.esm.js',
    import: '{ DishwasherIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: DocSettingIcon',
    path: './dist/icons.esm.js',
    import: '{ DocSettingIcon }',
    running: false,
    limit: '843 B',
  },
  {
    name: '> tree-shaking: DragAreaIcon',
    path: './dist/icons.esm.js',
    import: '{ DragAreaIcon }',
    running: false,
    limit: '945 B',
  },
  {
    name: '> tree-shaking: EditFillIcon',
    path: './dist/icons.esm.js',
    import: '{ EditFillIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: EditIcon',
    path: './dist/icons.esm.js',
    import: '{ EditIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: EmailAtIcon',
    path: './dist/icons.esm.js',
    import: '{ EmailAtIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: EmailIcon',
    path: './dist/icons.esm.js',
    import: '{ EmailIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: EnvelopeIcon',
    path: './dist/icons.esm.js',
    import: '{ EnvelopeIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ExitDevicesIcon',
    path: './dist/icons.esm.js',
    import: '{ ExitDevicesIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ExitIcon',
    path: './dist/icons.esm.js',
    import: '{ ExitIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: FacebookIcon',
    path: './dist/icons.esm.js',
    import: '{ FacebookIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: FileImageFillIcon',
    path: './dist/icons.esm.js',
    import: '{ FileImageFillIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: FileImageIcon',
    path: './dist/icons.esm.js',
    import: '{ FileImageIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: FolderOpenIcon',
    path: './dist/icons.esm.js',
    import: '{ FolderOpenIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: FreeHiddenIcon',
    path: './dist/icons.esm.js',
    import: '{ FreeHiddenIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: FridgeIcon',
    path: './dist/icons.esm.js',
    import: '{ FridgeIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: FullscreenIcon',
    path: './dist/icons.esm.js',
    import: '{ FullscreenIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: GoogleIcon',
    path: './dist/icons.esm.js',
    import: '{ GoogleIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: HeartIcon',
    path: './dist/icons.esm.js',
    import: '{ HeartIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: HelperIcon',
    path: './dist/icons.esm.js',
    import: '{ HelperIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: HiddenBoldIcon',
    path: './dist/icons.esm.js',
    import: '{ HiddenBoldIcon }',
    running: false,
    limit: '851 B',
  },
  {
    name: '> tree-shaking: HiddenIcon',
    path: './dist/icons.esm.js',
    import: '{ HiddenIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: IdBadgeIcon',
    path: './dist/icons.esm.js',
    import: '{ IdBadgeIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: IdIcon',
    path: './dist/icons.esm.js',
    import: '{ IdIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: InfoIcon',
    path: './dist/icons.esm.js',
    import: '{ InfoIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: InstagramIcon',
    path: './dist/icons.esm.js',
    import: '{ InstagramIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: InstructionIcon',
    path: './dist/icons.esm.js',
    import: '{ InstructionIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: InternetIcon',
    path: './dist/icons.esm.js',
    import: '{ InternetIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: KeyFillIcon',
    path: './dist/icons.esm.js',
    import: '{ KeyFillIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: KeyIcon',
    path: './dist/icons.esm.js',
    import: '{ KeyIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: LabelSortIcon',
    path: './dist/icons.esm.js',
    import: '{ LabelSortIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: LayerIcon',
    path: './dist/icons.esm.js',
    import: '{ LayerIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: LegalInfoIcon',
    path: './dist/icons.esm.js',
    import: '{ LegalInfoIcon }',
    running: false,
    limit: '912 B',
  },
  {
    name: '> tree-shaking: LinkIcon',
    path: './dist/icons.esm.js',
    import: '{ LinkIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ListIcon',
    path: './dist/icons.esm.js',
    import: '{ ListIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ListPhotoIcon',
    path: './dist/icons.esm.js',
    import: '{ ListPhotoIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: LoaderIcon',
    path: './dist/icons.esm.js',
    import: '{ LoaderIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: LockCloseIcon',
    path: './dist/icons.esm.js',
    import: '{ LockCloseIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: LockOpenIcon',
    path: './dist/icons.esm.js',
    import: '{ LockOpenIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: LoginFillIcon',
    path: './dist/icons.esm.js',
    import: '{ LoginFillIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: LoginIcon',
    path: './dist/icons.esm.js',
    import: '{ LoginIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: MapMarkerIcon',
    path: './dist/icons.esm.js',
    import: '{ MapMarkerIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: MapPinIcon',
    path: './dist/icons.esm.js',
    import: '{ MapPinIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: MapProgressIcon',
    path: './dist/icons.esm.js',
    import: '{ MapProgressIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: MessagesIcon',
    path: './dist/icons.esm.js',
    import: '{ MessagesIcon }',
    running: false,
    limit: '1.35 KB',
  },
  {
    name: '> tree-shaking: MetroIcon',
    path: './dist/icons.esm.js',
    import: '{ MetroIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: MetroRoundedIcon',
    path: './dist/icons.esm.js',
    import: '{ MetroRoundedIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: MicrowaveIcon',
    path: './dist/icons.esm.js',
    import: '{ MicrowaveIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: MinusIcon',
    path: './dist/icons.esm.js',
    import: '{ MinusIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: MoreIcon',
    path: './dist/icons.esm.js',
    import: '{ MoreIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: NewListIcon',
    path: './dist/icons.esm.js',
    import: '{ NewListIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: NextIcon',
    path: './dist/icons.esm.js',
    import: '{ NextIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: NotIndicatedIcon',
    path: './dist/icons.esm.js',
    import: '{ NotIndicatedIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: NotPublishedIcon',
    path: './dist/icons.esm.js',
    import: '{ NotPublishedIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: NotifyNoIcon',
    path: './dist/icons.esm.js',
    import: '{ NotifyNoIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: NotifyYesIcon',
    path: './dist/icons.esm.js',
    import: '{ NotifyYesIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: NumberA1Icon',
    path: './dist/icons.esm.js',
    import: '{ NumberA1Icon }',
    running: false,
  },
  {
    name: '> tree-shaking: NumberLifeIcon',
    path: './dist/icons.esm.js',
    import: '{ NumberLifeIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: NumberMtsIcon',
    path: './dist/icons.esm.js',
    import: '{ NumberMtsIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: NumberPhoneIcon',
    path: './dist/icons.esm.js',
    import: '{ NumberPhoneIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: OkIcon',
    path: './dist/icons.esm.js',
    import: '{ OkIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PaidIcon',
    path: './dist/icons.esm.js',
    import: '{ PaidIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PanoramaIcon',
    path: './dist/icons.esm.js',
    import: '{ PanoramaIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ParametersIcon',
    path: './dist/icons.esm.js',
    import: '{ ParametersIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PasswordChangeIcon',
    path: './dist/icons.esm.js',
    import: '{ PasswordChangeIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PaymentsIcon',
    path: './dist/icons.esm.js',
    import: '{ PaymentsIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PedestrianIcon',
    path: './dist/icons.esm.js',
    import: '{ PedestrianIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PhoneIcon',
    path: './dist/icons.esm.js',
    import: '{ PhoneIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PhonesIcon',
    path: './dist/icons.esm.js',
    import: '{ PhonesIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PhotosIcon',
    path: './dist/icons.esm.js',
    import: '{ PhotosIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PlusIcon',
    path: './dist/icons.esm.js',
    import: '{ PlusIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: PriceIcon',
    path: './dist/icons.esm.js',
    import: '{ PriceIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ProfessionalIcon',
    path: './dist/icons.esm.js',
    import: '{ ProfessionalIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ProfileIcon',
    path: './dist/icons.esm.js',
    import: '{ ProfileIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ProfileProIcon',
    path: './dist/icons.esm.js',
    import: '{ ProfileProIcon }',
    running: false,
    limit: '1.21 KB',
  },
  {
    name: '> tree-shaking: ProhibitedIcon',
    path: './dist/icons.esm.js',
    import: '{ ProhibitedIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: QuickInternetIcon',
    path: './dist/icons.esm.js',
    import: '{ QuickInternetIcon }',
    running: false,
    limit: '940 B',
  },
  {
    name: '> tree-shaking: ReadIcon',
    path: './dist/icons.esm.js',
    import: '{ ReadIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: RemoveIcon',
    path: './dist/icons.esm.js',
    import: '{ RemoveIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SavedFiltersBoldIcon',
    path: './dist/icons.esm.js',
    import: '{ SavedFiltersBoldIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SavedFiltersFillIcon',
    path: './dist/icons.esm.js',
    import: '{ SavedFiltersFillIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SavedFiltersIcon',
    path: './dist/icons.esm.js',
    import: '{ SavedFiltersIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SearchIcon',
    path: './dist/icons.esm.js',
    import: '{ SearchIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SelectBurgerIcon',
    path: './dist/icons.esm.js',
    import: '{ SelectBurgerIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SendIcon',
    path: './dist/icons.esm.js',
    import: '{ SendIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ServiceInfoIcon',
    path: './dist/icons.esm.js',
    import: '{ ServiceInfoIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ShareIcon',
    path: './dist/icons.esm.js',
    import: '{ ShareIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SiteIcon',
    path: './dist/icons.esm.js',
    import: '{ SiteIcon }',
    running: false,
    limit: '866 B',
  },
  {
    name: '> tree-shaking: SlidersIcon',
    path: './dist/icons.esm.js',
    import: '{ SlidersIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SocialNetworksIcon',
    path: './dist/icons.esm.js',
    import: '{ SocialNetworksIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SortIcon',
    path: './dist/icons.esm.js',
    import: '{ SortIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: StarIcon',
    path: './dist/icons.esm.js',
    import: '{ StarIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: StatisticsIcon',
    path: './dist/icons.esm.js',
    import: '{ StatisticsIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: StreetIcon',
    path: './dist/icons.esm.js',
    import: '{ StreetIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SuccessIcon',
    path: './dist/icons.esm.js',
    import: '{ SuccessIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: SuccessRoundedIcon',
    path: './dist/icons.esm.js',
    import: '{ SuccessRoundedIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: TelegramIcon',
    path: './dist/icons.esm.js',
    import: '{ TelegramIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: TwitterIcon',
    path: './dist/icons.esm.js',
    import: '{ TwitterIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: UpdateIcon',
    path: './dist/icons.esm.js',
    import: '{ UpdateIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: ViberIcon',
    path: './dist/icons.esm.js',
    import: '{ ViberIcon }',
    running: false,
    limit: '942 B',
  },
  {
    name: '> tree-shaking: VisibleBoldIcon',
    path: './dist/icons.esm.js',
    import: '{ VisibleBoldIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: VisibleIcon',
    path: './dist/icons.esm.js',
    import: '{ VisibleIcon }',
    running: false,
    limit: '786 B',
  },
  {
    name: '> tree-shaking: WarningIcon',
    path: './dist/icons.esm.js',
    import: '{ WarningIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: WashingMachineIcon',
    path: './dist/icons.esm.js',
    import: '{ WashingMachineIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: WhatsappIcon',
    path: './dist/icons.esm.js',
    import: '{ WhatsappIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: WorkerIcon',
    path: './dist/icons.esm.js',
    import: '{ WorkerIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: YandexIcon',
    path: './dist/icons.esm.js',
    import: '{ YandexIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: YoutubeIcon',
    path: './dist/icons.esm.js',
    import: '{ YoutubeIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: castIconProps',
    path: './dist/icons.esm.js',
    import: '{ castIconProps }',
    running: false,
  },
  {
    name: '> tree-shaking: GoogleNoFillIcon',
    path: './dist/icons.esm.js',
    import: '{ GoogleNoFillIcon }',
    running: false,
  },
  {
    name: '> tree-shaking: InstagramNoFillIcon',
    path: './dist/icons.esm.js',
    import: '{ InstagramNoFillIcon }',
    running: false,
  },
];
